[package]
name = "app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lib_demo = { git = "https://github.com/katayama8000/crates-publish-minimal", features = [
    "second",
], default-features = false }
tokio = { version = "1.35.0", features = ["full"] }
mockito = "1.5.0"
reqwest = { version = "0.12.8", features = ["json"] }
serde = { version = "1.0.213", features = ["derive"] }
serde_json = "1.0.132"
serde_derive = "1.0.193"
serde_with = "3.11.0"
anyhow = "1.0.91"
num-traits = "0.2.19"
mockall = "0.13.0"
chrono = "0.4.38"
chrono-tz = "0.10.0"
supabase_rs = "0.4.0"
dotenv = "0.15.0"
thiserror = "1.0.65"
scraper = "0.20.0"
url = "2.5.2"
percent-encoding = "2.3.1"
gyazo_client = "0.2.7"
expo_push_notification_client = "0.5.0"

[package.metadata.scripts]
run = "cargo run"
test = "cargo test"

[features]
default = []
japanese = []
basic = []
extra = []
