[package]
name = "app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lib_demo = { git = "https://github.com/katayama8000/crates-publish-minimal", features = [
    "second",
], default-features = false }
tokio = { version = "1.35.0", features = ["full"] }
mockito = "1.2.0"
reqwest = { version = "0.12.3", features = ["json"] }
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
serde_derive = "1.0.193"
serde_with = "3.4.0"
anyhow = "1.0.80"
num-traits = "0.2.18"
mockall = "0.12.1"
chrono = "0.4.37"
chrono-tz = "0.9.0"
supabase_rs = "0.3.1"
dotenv = "0.15.0"
thiserror = "1.0.61"
scraper = "0.19.0"
url = "2.5.2"
percent-encoding = "2.3.1"

[package.metadata.scripts]
run = "cargo run"
test = "cargo test"

[features]
default = []
japanese = []
basic = []
extra = []
